config/routes.rb
Todo::Application.routes.draw do
  resources :categories do
    resources :lists do
      resources :tasks
    end
end

root :to => 'categories#index'

end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :description, :name

  has_many :lists
end

app/models/list.rb
class List < ActiveRecord::Base
  belongs_to :category
  attr_accessible :description, :name, :category_id

  validates_presence_of :category_id

  has_many :tasks

end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :list
  attr_accessible :description, :name, :list_id

  validates_presence_of :list_id
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @categories }
    end
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    @category = Category.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @category }
    end
  end

  # GET /categories/new
  # GET /categories/new.json
  def new
    @category = Category.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @category }
    end
  end

  # GET /categories/1/edit
  def edit
    @category = Category.find(params[:id])
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(params[:category])

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render json: @category, status: :created, location: @category }
      else
        format.html { render action: "new" }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /categories/1
  # PUT /categories/1.json
  def update
    @category = Category.find(params[:id])

    respond_to do |format|
      if @category.update_attributes(params[:category])
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category = Category.find(params[:id])
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController

  before_filter :load_category

  # GET /lists
  # GET /lists.json
  def index
    @lists = @category.lists

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @lists }
    end
  end

  # GET /lists/1
  # GET /lists/1.json
  def show
    @list = List.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @list }
    end
  end

  # GET /lists/new
  # GET /lists/new.json
  def new
    @list = List.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @list }
    end
  end

  # GET /lists/1/edit
  def edit
    @list = List.find(params[:id])
  end

  # POST /lists
  # POST /lists.json
  def create
    @list = List.new(params[:list].merge({category_id: @category.id}))

    respond_to do |format|
      if @list.save
        format.html { redirect_to [@category, @list], notice: 'List was successfully created.' }
        format.json { render json: @list, status: :created, location: @list }
      else
        format.html { render action: "new" }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /lists/1
  # PUT /lists/1.json
  def update
    @list = List.find(params[:id])

    respond_to do |format|
      if @list.update_attributes(params[:list])
        format.html { redirect_to [@category, @list], notice: 'List was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lists/1
  # DELETE /lists/1.json
  def destroy
    @list = List.find(params[:id])
    @list.destroy

    respond_to do |format|
      format.html { redirect_to category_lists_url(@category) }
      format.json { head :no_content }
    end
  end

  private

  def load_category
    @category = Category.find(params['category_id'])
  end


end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  before_filter :load_category_and_list

  # GET /tasks
  # GET /tasks.json
  def index
    @tasks = @list.tasks

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tasks }
    end
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
    @task = Task.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @task }
    end
  end

  # GET /tasks/new
  # GET /tasks/new.json
  def new
    @task = Task.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @task }
    end
  end

  # GET /tasks/1/edit
  def edit
    @task = Task.find(params[:id])
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(params[:task].merge({list_id: @list.id}))

    respond_to do |format|
      if @task.save
        format.html { redirect_to [@category, @list, @task], notice: 'Task was successfully created.' }
        format.json { render json: @task, status: :created, location: @task }
      else
        format.html { render action: "new" }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /tasks/1
  # PUT /tasks/1.json
  def update
    @task = Task.find(params[:id])

    respond_to do |format|
      if @task.update_attributes(params[:task])
        format.html { redirect_to [@category, @list, @task], notice: 'Task was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task = Task.find(params[:id])
    @task.destroy

    respond_to do |format|
      format.html { redirect_to category_list_tasks_url(@category, @list) }
      format.json { head :no_content }
    end
  end

  private

  def load_category_and_list
    @category = Category.find(params['category_id'])
    @list = List.find(params['list_id'])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/categories/_form.html.haml
= simple_form_for(@category) do |f|
  = f.error_notification
  .form-inputs
    = f.input :name
    = f.input :description
  .form-actions
    = f.button :submit

app/views/categories/edit.html.haml
%h1 Editing category
= render 'form'
= link_to 'Show', @category
|
\#{link_to 'Back', categories_path}

app/views/categories/index.html.haml
%h1 Categories

%table.categories
  %tr
    %th Name
    %th Description
    %th
    %th
    %th
  - @categories.each do |category|
    %tr.category
      %td.name_field= category.name
      %td.description_field= category.description
      %td= link_to 'Show', category
      %td= link_to 'Edit', edit_category_path(category)
      %td= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' }
%br/
= link_to 'New Category', new_category_path

app/views/categories/new.html.haml
%h1 New category
= render 'form'
= link_to 'Back', categories_path

app/views/categories/show.html.haml
%h1= "Category: #{@category.name}"

%p#notice= notice

%p.description_field
  %b Description:
  = @category.description
= link_to 'Edit', edit_category_path(@category)
|
\#{link_to 'Back', categories_path}
|
\#{link_to 'New List', new_category_list_path(@category)}

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Todo</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/lists/_form.html.haml
= simple_form_for([@category, @list]) do |f|
  = f.error_notification
  .form-inputs
    = f.input :name
    = f.input :description
  .form-actions
    = f.button :submit

app/views/lists/edit.html.haml
%h1 Editing list
= render 'form'
= link_to 'Show', [@category, @list]
|
\#{link_to 'Back', category_lists_path(@category)}

app/views/lists/index.html.haml
%h1 Lists

%table.lists
  %tr
    %th Name
    %th Description
    %th
    %th
    %th
  - @lists.each do |list|
    %tr.list
      %td.name_field= list.name
      %td.description_field= list.description
      %td= link_to 'Show', category_list_path(@category, list)
      %td= link_to 'Edit', edit_category_list_path(@category, list)
      %td= link_to 'Destroy', category_list_path(@category, list), method: :delete, data: { confirm: 'Are you sure?' }
%br/
= link_to 'New List', new_category_list_path(@category)

app/views/lists/new.html.haml
%h1 New list
= render 'form'
= link_to 'Back', category_lists_path(@category)

app/views/lists/show.html.haml
%h1= "List: #{@list.name}"

%p#notice= notice
%p.description_field
  %b Description:
  = @list.description
%p
  %b Category:
  = @list.category
= link_to 'Edit', edit_category_list_path(@category, @list)
|
\#{link_to 'Back', category_lists_path(@category)}
|
\#{link_to 'New Task', new_category_list_task_path(@category, @list)}

app/views/tasks/_form.html.haml
= simple_form_for([@category, @list, @task]) do |f|
  = f.error_notification
  .form-inputs
    = f.input :name
    = f.input :description
  .form-actions
    = f.button :submit

app/views/tasks/edit.html.haml
%h1 Editing task
= render 'form'
= link_to 'Show', [@category, @list, @task]
|
\#{link_to 'Back', category_list_tasks_path(@category, @list)}

app/views/tasks/index.html.haml
%h1 Tasks
%table.tasks
  %tr
    %th Name
    %th Description
    %th
    %th
    %th
  - @tasks.each do |task|
    %tr.task
      %td.name_field= task.name
      %td.description_field= task.description
      %td= link_to 'Show', category_list_task_path(@category, @list, task)
      %td= link_to 'Edit', edit_category_list_task_path(@category, @list, task)
      %td= link_to 'Destroy', category_list_task_path(@category, @list, task), method: :delete, data: { confirm: 'Are you sure?' }
%br/
= link_to 'New Task', new_category_list_task_path(@category, @list)

app/views/tasks/new.html.haml
%h1 New task
= render 'form'
= link_to 'Back', category_list_tasks_path(@category, @list)

app/views/tasks/show.html.haml
%h1= "Task: #{@task.name}"

%p#notice= notice
%p.description_field
  %b Description:
  = @task.description
%p
  %b List:
  = @task.list
= link_to 'Edit', edit_category_list_task_path(@category, @list, @task)
|
\#{link_to 'Back', category_list_tasks_path(@category, @list)}